import type { Technology } from '@/shared/types';

export const technologies: Technology[] = [
	{
		id: 'html',
		name: 'HTML5',
		category: 'frontend',
		acquiredYear: 2021,
		acquiredMonth: 9,
	},
	{
		id: 'css',
		name: 'CSS3',
		category: 'frontend',
		acquiredYear: 2021,
		acquiredMonth: 9,
	},
	{
		id: 'javascript',
		name: 'JavaScript (ES6+)',
		category: 'frontend',
		acquiredYear: 2021,
		acquiredMonth: 9,
	},
	{
		id: 'git',
		name: 'Git',
		category: 'devops',
		acquiredYear: 2021,
		acquiredMonth: 10,
	},
	{
		id: 'scrum',
		name: 'Scrum / Agile',
		category: 'process',
		acquiredYear: 2021,
		acquiredMonth: 11,
	},
	{
		id: 'java',
		name: 'Java',
		category: 'backend',
		acquiredYear: 2022,
		acquiredMonth: 1,
	},
	{
		id: 'junit',
		name: 'JUnit',
		category: 'testing',
		acquiredYear: 2022,
		acquiredMonth: 1,
	},
	{
		id: 'spring-boot',
		name: 'Spring Boot',
		category: 'backend',
		acquiredYear: 2022,
		acquiredMonth: 6,
	},
	{
		id: 'rest',
		name: 'REST APIs',
		category: 'backend',
		acquiredYear: 2022,
		acquiredMonth: 6,
	},
	{
		id: 'python',
		name: 'Python',
		category: 'backend',
		acquiredYear: 2022,
		acquiredMonth: 8,
	},
	{
		id: 'sass',
		name: 'Sass / SCSS',
		category: 'frontend',
		acquiredYear: 2022,
		acquiredMonth: 9,
	},
	{
		id: 'react',
		name: 'React',
		category: 'frontend',
		acquiredYear: 2023,
		acquiredMonth: 1,
	},
	{
		id: 'typescript',
		name: 'TypeScript',
		category: 'frontend',
		acquiredYear: 2023,
		acquiredMonth: 3,
	},
	{
		id: 'jest',
		name: 'Jest',
		category: 'testing',
		acquiredYear: 2023,
		acquiredMonth: 6,
	},
	{
		id: 'gitlab',
		name: 'GitLab',
		category: 'tools',
		acquiredYear: 2023,
		acquiredMonth: 9,
	},
	{
		id: 'jira',
		name: 'Jira',
		category: 'tools',
		acquiredYear: 2023,
		acquiredMonth: 9,
	},
	{
		id: 'confluence',
		name: 'Confluence',
		category: 'tools',
		acquiredYear: 2023,
		acquiredMonth: 9,
	},
	{
		id: 'sap-cx',
		name: 'SAP Commerce Cloud',
		category: 'backend',
		acquiredYear: 2024,
		acquiredMonth: 6,
	},
	{
		id: 'sonarqube',
		name: 'SonarQube',
		category: 'tools',
		acquiredYear: 2024,
		acquiredMonth: 7,
	},
	{
		id: 'bff',
		name: 'BFF architecture',
		category: 'backend',
		acquiredYear: 2024,
		acquiredMonth: 7,
	},
	{
		id: 'cicd',
		name: 'CI/CD',
		category: 'devops',
		acquiredYear: 2024,
		acquiredMonth: 7,
	},
	{
		id: 'cypress',
		name: 'Cypress',
		category: 'testing',
		acquiredYear: 2024,
		acquiredMonth: 8,
	},
	{
		id: 'vite',
		name: 'Vite',
		category: 'frontend',
		acquiredYear: 2024,
		acquiredMonth: 10,
	},
	{
		id: 'nextjs',
		name: 'Next.js',
		category: 'frontend',
		acquiredYear: 2025,
		acquiredMonth: 2,
	},
	{
		id: 'github-actions',
		name: 'GitHub Actions',
		category: 'devops',
		acquiredYear: 2025,
		acquiredMonth: 3,
	},
	{
		id: 'sentry',
		name: 'Sentry',
		category: 'tools',
		acquiredYear: 2026,
		acquiredMonth: 6,
	},
];
